### ISSUE TITLE
Offender popup inconsistent behavior

### ISSUE THREAD

**Issue by nathankota** [agrc/parole-and-probation#137]
#### Example 1

- Statewide map view
- Remove `Me` filter
- `Offender Name` filter = Hancock
- Select offender with first initial of "J"
- Click point 
- Receive "No offender at click location"
- Remove name from filter
- Zoom out two levels
- Filter same offender name
- Click point and popup works

#### Example 2
- Statewide map view
- Remove `Me` filter
- `Offender Number` filter =19383...
- Select the only result
- Click point 
- Receive "No offender at click location"
- Delete offender number
- Zoom out a few levels
- Filter for same offender number
- Click point and popup works

#### Example 3
Randomly clicked on points within the map area (and a little beyond) in the `Offender_Sample.PNG` in the [project folder](https://drive.google.com/drive/u/0/folders/1agcCNTsUPOi56NLIxR907U1fsOlKJtvR) and received the "No offender at click location" about 50% of the time. After about 5-7 minutes, continued clicking in the area on same points and not receiving any errors.

**Comment by steveoh** [comment]
I think what was happening here is that at the zoomed out scales, some points weren't being rendered by the view. When zooming in, the points would be rendered but the layer view wasn't aware of them. Fortunately, this bug was fixed in the upstream javascript api that will be released in April. I am using the nightly builds and can verify that our issue is fixed. We will want the production version deployed as soon as it is available for stability reasons but for now I will deploy to test with the nightly build. Hopefully no other issues arise from this decision.
